ECommerce/Models/Order.cs
namespace ECommerce.Models
{
    public class Order
    {
        public Guid Id { get; set; }
        public DateTime OrderDate { get; set; }
        public double NetAmount { get; set; }
        public double GrossAmount { get; set; }
        public double TaxAmount { get; set; }
        public double Discount { get; set; }

        public string? UserId { get; set; }
        public User User { get; set; }
        
        public Guid? OrderStatusId { get; set; }
        public OrderStatus? OrderStatus { get; set; }
        
        public Guid? ShippingId { get; set; }
        public Shipping? Shipping { get; set; }
                
        public IEnumerable<OrderItem> OrderItems { get; set; }
    }
}

ECommerce/Controllers/OrderController.cs
using ECommerce.Models;
using ECommerce.Services.Interface;
using ECommerce.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.RenderTree;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECommerce.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IOrderStatusService _orderStatusService;
        private readonly UserManager<User> _userManager;
        
        public OrderController(IOrderService orderService, IOrderStatusService orderStatusService, UserManager<User> userManager)
        {
            _orderService = orderService;
            _orderStatusService = orderStatusService;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            var order = await _orderService.GetAllOrdersAsync(pageNumber, pageSize);
            var orderStatusList = await _orderStatusService.GetAllOrderStatusAsync();
            ViewData["orderStatusId"] = new SelectList(orderStatusList, "Id", "Status");
            return View(order);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            var order = await _orderService.GetOrderByIdAsync(id);
            ViewData["orderStatusId"] = new SelectList(await _orderStatusService.GetAllOrderStatusAsync(), "Id", "Status");

            return View(order);
        }
        public async Task<IActionResult> CreateOrder(CartViewModel cart, int pageNumber=1, int pageSize=10)
        {
            var user = await _userManager.GetUserAsync(User);
            await _orderService.CreateOrderAsync(user.Id, cart.ShippingId);
            var orders = await _orderService.GetOrderByUserIdAsync(user.Id, pageNumber, pageSize);
            var order = orders.LastOrDefault();
            cart.OrderId = order.Id;
            return RedirectToAction("Add", "Payment", cart);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateOrderStatus([FromBody]Order order)
        {
            await _orderService.UpdateOrderStatusAsync(order.Id, (Guid)order.OrderStatusId);
            var referer = Request.Headers["Referer"].ToString();
            if (!string.IsNullOrEmpty(referer))
            {
                return Redirect(referer);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

ECommerce/Views/Order/Details.cshtml
@model ECommerce.ViewModel.OrderViewModel
@{
    ViewData["Title"] = "OrderDetails";
}

<div class="container">
    <div class="d-flex justify-content-between">
        <a class="btn btn-primary" asp-action="Index">Back</a>
        @*@<a class="btn btn-primary" onclick="window.location.href='@Url.Action("Invoice", "Orders", new { id = Model.Id })'">>Generate Invoice</a>*@
    </div>
    <h4 class="text-center">Order Details</h4>
    <hr />
    <dl class="row">
        <div class="col">
            <dl class="row offset-sm-2">
                <dt class="col-sm-2">
                    Name
                </dt>
                <dd class="col-sm-3">
                    @Html.DisplayFor(model => model.User.FirstName) @Html.DisplayFor(model => model.User.LastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.OrderDate)
                </dt>
                <dd class="col-sm-3">
                    @Html.DisplayFor(model => model.OrderDate)
                </dd>
            </dl>
            <dl class="row offset-sm-2">
                <dt class="col-sm-2">
                    Address
                </dt>
                <dd class="col-sm-3">
                    @Html.DisplayFor(model=>model.Shipping.Address)
                </dd>
                <dt class="col-sm-2">
                    Phone Number
                </dt>
                <dd class="col-sm-3">
                    @Html.DisplayFor(model => model.User.PhoneNumber)
                </dd>
            </dl>
            <dl class="row offset-sm-2">
                <dt class="col-sm-2">
                    Email
                </dt>
                <dd class="col-sm-3">
                    @Html.DisplayFor(model => model.User.Email)
                </dd>
            </dl>

        </div>

        <div class="row">
            <div class="col">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>
                                Product Name
                            </th>
                            <th>
                                Product
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th>
                                Rate
                            </th>
                            <th>
                                Total Price
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.OrderItems)
                        {
                            <tr>
                                <td class="col-sm-3">
                                    Product
                                </td>
                                <td class="col-sm-3">
                                    <div class="d-flex align-items-center">
                                        <img src="@item.ImageUrl" class="img-fluid" alt="Sofa" style="width: 120px; border-radius: 10px;">
                                    </div>
                                </td>
                                <td class="col-sm-2">
                                    @Html.DisplayFor(model => item.Quantity)
                                </td>

                                <td class="col-sm-2">
                                    @Html.DisplayFor(model => item.UnitPrice)
                                </td>
                                <td class="col-sm-2">
                                    @Html.DisplayFor(Model => item.TotalPrice)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>


    </dl>
</div>

ECommerce/Views/Order/Index.cshtml
@using ECommerce.Helper
@model PaginatedList<ECommerce.Models.Order>

@{
    ViewData["Title"] = "Orders";
    int serialNumber = 1 + (Model.PageNumber - 1) * 10;
    var orderStatusList = ViewBag.orderStatusId as SelectList;
    var statusList = orderStatusList.Where(item=>(item as SelectListItem)?.Text != "Cancelled").ToList();
    ViewBag.StatusList = new SelectList(statusList, "Value", "Text");
}

<h1 class="text-center">Orders</h1>
<div class="container">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    S.N.
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Order Date
                </th>
                <th>
                    Order Status
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.Items)
            {
                <tr data-url="@Url.Action("Details", new { id = item.Id })" onclick="window.location=this.dataset.url">
                    <td>
                        @serialNumber
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.FirstName)
                        @Html.DisplayFor(modelItem => item.User.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        <form method="post" asp-controller="Order" asp-action="UpdateOrderStatus" id="statusForm_@item.Id">
                            <div class="form-group">
                                <input type="hidden" name="orderId" value="@item.Id">
                                @if(item.OrderStatus.Status == "Cancelled")
                                {
                                    <select class="form-control" disabled>
                                        <option selected>Cancelled</option>
                                    </select>
                                }
                                else
                                {
                                    <select asp-for="@item.OrderStatusId" name="orderStatusId" class="form-control" asp-items="ViewBag.StatusList" onclick="event.stopPropagation();" onchange="submitForm(`@item.Id`);">
                                        <option>Select Order Status</option>
                                    </select>
                                }
                            </div>
                        </form>
                    </td>
                </tr>
                serialNumber++;
            }
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @if (Model.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber - 1 })" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { pageNumber = i })">@i</a>
                </li>
            }

            @if (Model.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber + 1 })" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>
<div class="modal fade" id="statusModal" tabindex="-1" aria-labelledby="statusModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Status Updated.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div> 
<script>
    function submitForm(orderId) {    
        var form = document.getElementById('statusForm_' + orderId);
        var orderStatusId = form.querySelector('select[name="orderStatusId"]').value;

        fetch('@Url.Action("UpdateOrderStatus", "Order")', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                Id: orderId,
                orderStatusId: orderStatusId
            })
        })
            .then(response => {
                if (response.ok) {
                    var modal = new bootstrap.Modal(document.getElementById('statusModal'));
                    modal.show();
                } else {
                    console.error("Failed to update the order status.");
                }
            })
            .catch(error => console.error('Error submitting the status form:', error));
    }
</script>