ECommerce/Controllers/CartController.cs
using AutoMapper;
using ECommerce.Models;
using ECommerce.Services.Interface;
using ECommerce.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECommerce.Controllers
{
    public class CartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartService;
        private readonly IPaymentMethodService _paymentMethodService;
        private readonly ILogger<CartController> _logger;
        private readonly IMapper _mapper;
        public CartController(ICartService cartService, UserManager<User> userManager, IPaymentMethodService paymentMethodService,ILogger<CartController> logger, IMapper mapper)
        {
            _cartService = cartService;
            _paymentMethodService = paymentMethodService;
            _userManager = userManager;
            _logger = logger;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }
            var cart = await _cartService.GetCartByUserIdAsync(user.Id);
            ViewData["PaymentMethodId"] = new SelectList(await _paymentMethodService.GetAllPaymentMethodAsync(), "Id", "Method");
            return View(cart);
        }
        [HttpPost]
        public async Task<JsonResult> AddToCart([FromBody] ShopViewModel model)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    
                    return Json(new { success = true, message = "Please Login First.", redirectUrl = "Identity/Account/Login" });
                }

                Console.WriteLine("User logged in: " + user.Id);

                Guid productId = (Guid)model.ProductId;
                Console.WriteLine("Adding product to cart: " + productId);

                var result = await _cartService.AddToCartAsync(user.Id, productId, 1);
                var cart = await _cartService.GetCartByUserIdAsync(user.Id);
                var cartItemCount = cart.CartItems.Count();

                Console.WriteLine("Product added to cart, item count: " + cartItemCount);

                if (result)
                {
                    return Json(new { success = true, message = "Product added to cart.", cartItemCount });
                }
                else
                {
                    return Json(new { success = true, message = "Product already in cart.", cartItemCount });
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error adding product to cart: " + ex.Message);
                return Json(new { success = false, message = "An error occurred while adding the product to the cart." });
            }
        }
        public async Task<IActionResult> UpdateQuantity(Guid CartItemId, int quantity)
        {
            var user = await _userManager.GetUserAsync(User);
            await _cartService.UpdateCartItemQuantityAsync(user.Id, CartItemId, quantity);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UpdateCartItem(Guid CartItemId, bool selected)
        {
            var user = await _userManager.GetUserAsync(User);
            await _cartService.UpdateCartItemAsync(user.Id, CartItemId, selected);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(Guid cartItemid)
        {
            var user = await _userManager.GetUserAsync(User);
            await _cartService.RemoveFromCartAsync(user.Id, cartItemid);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> BuyNow(Guid productId, int quantity)
        {
            var model = new ShopViewModel
            {
                ProductId = productId
            };
            await AddToCart(model);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> GetCartItemCount()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Json(new { cartItemCount = 0 });
            }
            var cart = await _cartService.GetCartByUserIdAsync(user.Id);
            var cartItemCount = cart?.CartItems?.Count() ?? 0;
            return Json(new { cartItemCount });
        }
        public async Task<IActionResult> ClearCart()
        {
            var user = await _userManager.GetUserAsync(User);
            await _cartService.ClearCartAsync(user.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ECommerce/Controllers/ShopController.cs
using ECommerce.Services.Implementation;
using ECommerce.Services.Interface;
using ECommerce.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECommerce.Controllers
{
    public class ShopController : Controller
    {
        private readonly IShopService _shopService;
        private readonly ICategoryServices _categoryServices;
        public ShopController(IShopService shopService, ICategoryServices categoryServices)
        {
            _shopService = shopService;
            _categoryServices = categoryServices;
        }
        public async Task<IActionResult> ShopView(List<Guid>? categoryId, double? minPrice, double? maxPrice, string sortOrder = "", int pageNumber = 1, int pageSize = 8, string searchString = "")
        {
            var products = await _shopService.GetShopViewAsync(categoryId, minPrice, maxPrice,  sortOrder, pageNumber, pageSize, searchString);
            ViewData["CategoryId"]  = new SelectList(await _categoryServices.GetAllCategoriesAsync(), "Id", "Name");
            return View(products);
        }
    }
}

ECommerce/Views/Shop/ShopView.cshtml
@model ECommerce.ViewModel.ShopViewModel
@{
    ViewData["title"] = "Shop";
    string searchString = ViewContext.HttpContext.Request.Query["searchString"].ToString();
}
<div class="row">
    <div class="col-2 d-flex ">
        <div class="navbar flex-column">
            <form method="get" role="search" action="@Url.Action("ShopView", "Shop")">
                <input name="searchString" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                       value="@searchString" />
                <button class="btn btn-outline-success" type="submit">Search</button>

                <select asp-for="CategoryId" asp-items="ViewBag.CategoryId" onchange="submit();">
                    <option>Categories</option>
                </select>
            </form>
        </div>
    </div>
    <div class="col-10">
    <div class="row">
        @if (string.IsNullOrEmpty(searchString)) { <p class="h3"> All Products</p> }
        else{ <p class="h3">Search results for "@searchString"</p>}
    </div>
    <div class="row">
        @foreach (var product in Model.Products.Items)
        {
            if (product != null)
            {
                <div class="col-md-3 mb-3">
                    <div class="card shadow h-100" data-url="@Url.Action("Details", "Product", new { id = product.Id })" onclick="window.location=this.dataset.url">
                        <img src="@product.ImageUrl" class="card-img-top" alt="...">
                        <div class="card-body">
                            <div class="row d-flex">
                                <div class="col">
                                    <h5 class="card-title">@product.Name</h5>
                                    <p class="card-text">Rs @product.Price/-</p>
                                    @if(product.StockQuantity < 0)
                                    {
                                        <p class="disabled">(Out of Stock)</p>
                                    }
                                </div>
                                <div class="col">
                                    <button class="btn btn-outline-primary addToCartBtn" data-productId="@product.Id" onclick="event.stopPropagation(); addToCart(this)">
                                        <iconify-icon class="cart" icon="solar:cart-line-duotone" noobserver></iconify-icon>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @if (Model.Products.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("ShopVIew", new { pageNumber = Model.Products.PageNumber - 1 })" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (int i = 1; i <= Model.Products.TotalPages; i++)
            {
                <li class="page-item @(i == Model.Products.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("ShopView", new { pageNumber = i })">@i</a>
                </li>
            }

            @if (Model.Products.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("ShopView", new { pageNumber = Model.Products.PageNumber + 1 })" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p id="cartModalMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
                <a href="/cart" class="btn btn-success" id="cart-login-btn">View Cart</a>
            </div>
        </div>
    </div>
</div>
<script>
    function addToCart(button){
        const productId = button.getAttribute("data-productId");
        const quantity = 1;
        console.log(productId)
        console.log('@Url.Action("AddToCart", "Cart")');

        fetch('@Url.Action("AddToCart", "Cart")', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ productId: productId, quantity: quantity })
        })
            .then(response => {
                console.log("Response status: ", response.status);
                if (!response.ok) {
                    throw new Error('Network response was not ok.');
                }
                return response.json();
            })
            .then(data => {
                if (data.success) {
                    const modalMessage = document.getElementById('cartModalMessage');
                    modalMessage.innerText = data.message;
                    if (data.message === "Please Login First.") {
                        const cartBtn = document.getElementById('cart-login-btn');
                        cartBtn.innerText = "Redirect to Login";
                    }
                    const cartModal = new bootstrap.Modal(document.getElementById('cartModal'));
                    cartModal.show();
                } else {
                    alert(data.message);
                }
            })
            .catch(error => {
                console.error('Error:', error.message);
                alert('An error occurred while adding the product to the cart. ' + error.message);
            });
    }
    function submit(){

    }
</script>